---
- hosts: all
  remote_user: inoue
  tasks:
    - include_tasks: tasks/apt_packages.yml
    - include_tasks: tasks/zsh.yml
    - include_tasks: tasks/tmux.yml
    - include_tasks: tasks/cuda_10_2.yml
    - include_tasks: tasks/docker.yml
    - include_tasks: tasks/nvidia_docker.yml
    - include_tasks: tasks/miniconda.yml
    - name: Reboot
      become: true
      reboot:
