---
- hosts: all
  remote_user: inoue
  become: true
  vars:
    home_dir: /home/inoue
  tasks:
    - include_tasks: tasks/apt_packages.yml
    - include_tasks: tasks/zsh.yml
    - include_tasks: tasks/tmux.yml
    - include_tasks: tasks/docker.yml
    - include_tasks: tasks/nvidia_docker.yml
