- name: Install docker's requirements
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    update_cache: yes
    state: latest

- name: Add docker gpg apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker repository to apt sources
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Install docker-ce
  apt:
    name: docker-ce
    update_cache: yes
    state: present
