- name: Download pin file
  become: true
  get_url:
    url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-ubuntu1804.pin
    dest: /etc/apt/preferences.d/cuda-repository-pin-600

- name: Add cuda apt key
  become: true
  apt_key:
    url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub
    state: present

- name: Add cuda to /etc/apt/sources.list.d
  become: true
  apt_repository:
    repo: deb http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64 /
    state: present

- name: Install cuda and nvidia-driver
  become: true
  apt:
    name: cuda
    state: present
    update_cache: yes
